"""create signals table

Revision ID: 0c5ed7e30040
Revises: b52273bea250
Create Date: 2026-06-10 18:40:06.391271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c5ed7e30040'
down_revision: Union[str, Sequence[str], None] = 'b52273bea250'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('market', sa.Enum('forex', 'crypto', 'stocks', 'indices', 'commodities', name='market_type'), nullable=False),
    sa.Column('direction', sa.Enum('buy', 'sell', name='signal_direction'), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=False),
    sa.Column('take_profit', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('open', 'tp_hit', 'sl_hit', 'expired', 'cancelled', name='signal_status'), nullable=False),
    sa.Column('source', sa.Enum('manual', 'tradingview', 'strategy', 'broker', name='signal_source'), nullable=False),
    sa.Column('risk_reward_ratio', sa.Float(), nullable=True),
    sa.Column('pips_risk', sa.Float(), nullable=True),
    sa.Column('pips_reward', sa.Float(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_status'), 'signals', ['status'], unique=False)
    op.create_index(op.f('ix_signals_symbol'), 'signals', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signals_symbol'), table_name='signals')
    op.drop_index(op.f('ix_signals_status'), table_name='signals')
    op.drop_table('signals')
    # ### end Alembic commands ###
