"""add ai score to signals

Revision ID: 8ccc9d199fd1
Revises: 17d2485344b4
Create Date: 2026-06-13 19:23:19.317458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ccc9d199fd1'
down_revision: Union[str, Sequence[str], None] = '17d2485344b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('signals', sa.Column('ai_score', sa.Integer(), nullable=True))
    op.add_column('signals', sa.Column('ai_grade', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('signals', 'ai_grade')
    op.drop_column('signals', 'ai_score')
    # ### end Alembic commands ###
