"""make created_by nullable

Revision ID: e9180373559a
Revises: 2973fdafdc6f
Create Date: 2026-06-11 18:33:47.702827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9180373559a'
down_revision: Union[str, Sequence[str], None] = '2973fdafdc6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('signals', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('signals', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
